{% set name = "gnuastro" %}
{% set version = "0.16" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: http://ftp.gnu.org/gnu/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 90c11d25bb05ad13710cb5f81179ed8173608a426fdffd8b2045862d5fdee22d
  patches:
    - 1fa93a020bae99b5e88867c8f8e6ff4b17acf0f6.patch

build:
  number: 1
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - automake
    - make
    - libtool
  host:
    - gsl
    - cfitsio
    - wcslib
    - jpeg
    - libtiff
    - libgit2
    - ghostscript
  run:
    - wcslib
    - libcurl
    - libcblas
    - libgit2
    - xz
    - zlib

test:
  commands:
    - test -f ${PREFIX}/lib/libgnuastro${SHLIB_EXT}  # [unix]
    - test -f ${PREFIX}/lib/libgnuastro.a  # [unix]
    - astarithmetic --help
    - astconvertt --help
    - astcosmiccal --help
    - astfits --help
    - astmkcatalog --help
    - astmkprof --help
    - aststatistics --help
    - astwarp --help
    - astbuildprog --help
    - astconvolve --help
    - astcrop --help
    - astmatch --help
    - astmknoise --help
    - astnoisechisel --help
    - asttable --help

about:
  home: https://www.gnu.org/software/gnuastro
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: COPYING
  summary: A GNU package consisting of various programs and library functions for the manipulation and analysis of astronomical data.

extra:
  recipe-maintainers:
    - sebastian-luna-valero
    - mohammad-akhlaghi  # upstream developer
