{% set name = "gnuastro" %}
{% set version = "0.20.60" %}

package:
  name: {{ name|lower }}_dev
  version: {{ version }}

source:
#  url: https://alpha.gnu.org/gnu/{{ name }}/{{ name }}-{{ version }}.tar.gz.lz
  url: https://alpha.gnu.org/gnu/gnuastro/gnuastro-0.20.60-d994.tar.lz
  sha256: f3c533bb6a648dd3c0619fdcf0b066b1f5081978946c0bd7f6e912f15eb4c1fe

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - gnuconfig  # [unix]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - automake
    - make
    - libtool
  host:
    - gsl
    - cfitsio
    - wcslib
    - libjpeg-turbo
    - libtiff
    - libgit2
    - ghostscript
  run:
    - wcslib
    - libcurl
    - libcblas
    - libgit2
    - xz
    - zlib

test:
  commands:
    - test -f ${PREFIX}/lib/libgnuastro${SHLIB_EXT}  # [unix]
    - test -f ${PREFIX}/lib/libgnuastro.a  # [unix]
    - astarithmetic --help
    - astconvertt --help
    - astcosmiccal --help
    - astfits --help
    - astmkcatalog --help
    - astmkprof --help
    - aststatistics --help
    - astwarp --help
    - astbuildprog --help
    - astconvolve --help
    - astcrop --help
    - astmatch --help
    - astmknoise --help
    - astnoisechisel --help
    - asttable --help

about:
  home: https://www.gnu.org/software/gnuastro
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: COPYING
  summary: A GNU package consisting of various programs and library functions for the manipulation and analysis of astronomical data.

extra:
  recipe-maintainers:
    - sebastian-luna-valero
    - mohammad-akhlaghi  # upstream developer
